srv_www:
    build: srv-www
    volumes:
        - ./volumes/var/www/php5-app:/var/www/php5-app
    tty: true

php5_fpm:
    build: php5-fpm
    expose:
        - 9009:9000
    volumes_from:
        - srv_www
    volumes:
        - ./volumes/var/log/:/var/log

nginx_fcgi_php:
    build: nginx-fcgi-php
    ports:
        - 8008:80
    links:
        - php5_fpm
    volumes:
        - ./volumes/var/cache/nginx/:/var/cache/nginx
        - ./volumes/var/log/nginx/:/var/log/nginx
